### PR TITLE
ci: version to 4.0.0 Micronaut 4.0.0-SNAPSHOT githubCoreBranch=4.0.x

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Comment by wetted** [comment]
This has some issues with three tests that worked on master but break now. But it doesn't break with this branch alone. If I change master from Micronaut 3.3.4 to 3.5.0, the same three tests break as well. I know at least one seems due to changes in the `BeanContext` refactoring that was done for Micronaut 3.5.0. Any ideas about this @dstepanov? Can you please have a look at `RateLimitingQueueFactorySpec`? I think that's a problem with changes to `BeanContext` or rather `DefaultBeanContext` in core. I don't know about the others yet (`ConfigMapResourceReconcilerSpec` and `ConfigMapResourceReconcilerWithFiltersSpec`).

**Review by sdelamo — APPROVED** [review]

**Comment by timyates** [comment]
The `Unsupported class file major version 61` error seems to be caused by cglib when Spock tries to create a `Stub` (in some situations)

I could work around it by adding 

```
configurations {
    testRuntimeClasspath {
        resolutionStrategy.dependencySubstitution {
            substitute module('cglib:cglib-nodep') using module('net.bytebuddy:byte-buddy:1.12.18')
        }
    }
}
```

To the builds in question (to replace cglib with byte-buddy at test runtime)

We add cglib in our internal tools

https://github.com/micronaut-projects/micronaut-build/blob/d3b3d0e7c4187af0c2c3d09986decc02322feccd/src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy#L85-L87

Should we be thinking about migrating to byte-buddy for 4.0.0?  I don't know about the state of either library enough to make a call...

@melix @sdelamo @graemerocher

**Comment by graemerocher** [comment]
Yes move to bytebuddy 

Cglib is not maintained anymore

**Comment by wetted** [comment]
> @wetted io.micronaut.build.shared.settings 6.0.1 is out which uses bytebuddy instead of cglib 🤞

Thanks @timyates . I'll make the change and push it.

**Comment by timyates** [comment]
Hmmm... fails on CI and fails differently locally

Did you get this passing locally @wetted ?

Maybe @alvarosanchez has seen the errors before?

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
The build is failing because the workflow is still calling a `dependencyUpdates` task that no longer exists.

In general, all workflows need to be updated "manually" comparing them with the project template. Also there are other workflows that should be removed (eg `dependency-update.yml`)

**Comment by wetted** [comment]
I'll fix the ci thing with workflows. 

It still has two test issues. One has to do with duplicate beans. The other is a failure with: `io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.kubernetes.client.operator.ConfigMapResourceReconciler] could not be loaded: Error instantiating bean of type [io.micronaut.kubernetes.client.operator.ControllerConfiguration]: Failed to resolve the `apiGroup` for class io.kubernetes.client.openapi.models.V1ConfigMap from discovery cache.`

**Comment by wetted** [comment]
This is PR still has three failing tests, but should be ready for Micronaut 4 otherwise, as far as I know.

**Comment by sdelamo** [comment]
@n0tl3ss could you merge master into this branch and see if it passes now?

**Comment by n0tl3ss** [comment]
Blocked by https://github.com/micronaut-projects/micronaut-core/issues/8593

**Comment by wetted** [comment]
Interesting about all the failures. When I run locally only `ConfigMapResourceReconcilerSpec` and `ConfigMapResourceReconcilerWithFiltersSpec` are failing.

**Comment by sdelamo** [comment]
I assume this is superseded by https://github.com/micronaut-projects/micronaut-kubernetes/pull/548

**Pull request closed without merging**
