### PR TITLE
Official k8s client

### PR DESCRIPTION
**Pull request by pgressa**
Fixes #266 
- introduce new module kubernetes-client
  - not yet part of discovery client to break compatibility
- pregenerates all Apis as micronaut beans

### CODE REVIEW

**Comment by pgressa** [comment]
It's new module so it doesn't have to go to the new major version. In new major version will go migration of discovery client to this new client.

**Comment by graemerocher** [comment]
Nice work. Will need some documentation as well.

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
Amazing! Great job!

However, there are test failures and checkstyle violations

**Comment by pgressa** [comment]
@alvarosanchez ok, now ready, tests are passing, both incluster and kubeconfig apis tested

**Review by alvarosanchez — APPROVED** [review]

**Pull request merged**
