### PR TITLE
build: update build plugin to 5.2.3

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Review by melix — APPROVED** [review]

**Comment by melix** [comment]
Fixes #443

**Comment by timyates** [comment]
@sdelamo As we needed to update Gradle for the new build plugin, I went the whole 9 yards and updated ready for 3.4.0 as well as fixing the bom

Also raised https://github.com/micronaut-projects/micronaut-kubernetes/issues/442 to move the examples to guides

**Comment by timyates** [comment]
I'm now wondering if we need to do something for the 3.3.x branch of micronaut to fix this there too (assuming this will only go into 3.4.x)

It's too late for my brain to accurately process versioning though...

**Comment by timyates** [comment]
I need to try and work out how to run these locally... 😮‍💨

**Comment by timyates** [comment]
I don't think my changes are causing the failure...  I may be wrong though, but it fails the same before *and after* my commit

**Comment by timyates** [comment]
This passes locally when executed in isolation...  Trying to think what it could be 🤔

**Comment by timyates** [comment]
That seems to be passing, I'll raise another PR for #443

**Comment by timyates** [comment]
I think this is ok now, the failure I believe is cause by a flakey test

Raised https://github.com/micronaut-projects/micronaut-kubernetes/pull/446 to update the report checker

**Pull request merged**
