### PR TITLE
Add Dekorate as an imported BOM

### PR DESCRIPTION
**Pull request by alvarosanchez**
Inestead of https://github.com/micronaut-projects/micronaut-platform/pull/62

### CODE REVIEW

**Comment by alvarosanchez** [comment]
@melix I noticed that this generates:

```xml
<dependency>
    <groupId>io.dekorate</groupId>
    <artifactId>dekorate-bom</artifactId>
    <version>${dekorate.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

However there is no such `dekorate.version` property:

```xml
<properties>
    <micronaut.kubernetes.version>5.0.0-M2</micronaut.kubernetes.version>
</properties>
```

What am I missing?

**Comment by melix** [comment]
You should make the `dekorate` version managed (use `managed-dekorate` instead of `dekorate`). Is `dekorate` specific to this project? Or should it live in `micronaut-kotlin`?

**Comment by alvarosanchez** [comment]
> You should make the `dekorate` version managed (use `managed-dekorate` instead of `dekorate`). 

🤦  thanks

> Is `dekorate` specific to this project? Or should it live in `micronaut-kotlin`?

Belongs here. The K stands for Kubernetes, not Kotlin

**Comment by alvarosanchez** [comment]
Blocked by https://github.com/dekorateio/dekorate/issues/1207

@melix is there any workaround for this problem meanwhile?

**Pull request closed without merging**
